---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-runner-secret
  namespace: forgejo-runner
spec:
  encryptedData:
    FORGEJO_INSTANCE_URL: AgBxFUH2u7noEpT2SBY5xKGz1Az/J3L66CF1kk0iwbrEDkxSU9b6uheAtCiNqmOO04vQOVfPYH/IgwpfN+gJwLgHg0D0mBxDeS9GZ/U8NXHNmBRNYAjHtIOYnxc3/JfR2ac0u3XktCH59iHVOK3t37hljjnEO4IFv+pozMxC/NGsSj+hUb4bp+KPsFjl/2/W3gtiiC880j+u8ts1OBVn54g66i+hrp1sP/nuhtD9HD4vFAdA7mclrRvf/zJz2aU0TkEBVE2Ch5agI4ffja2PO/DJojKVN3Lo9g5nexKYMVv6lwW2FkojEteoDCWQOHKosDgVfSHAZhSxWOwgOa5YmB5cBbKa6EKmmwLBBIr6JnVCQUdWszZ4MXnNR5CEMiikVmZwZL2JaQa8CtlG5GmtIzzWCOgJYXSYR+PDdsJIMqXnLuuLqeP4HflQsk6WIPCWTVjObEZJShZ9ymH3UVlLVtqlKKeF5i0lwhPD9XXjtZG4BTb1vsvRi+5eauaIRT0ybOFbEB2QikjZRm5aLGKweeGHuWjIbI2gEljFXRZgloCqLeg8BRUyE8O+MBeQ0XVUo4U1ETByZd9Wp0XbXynkqHU4GJCBKMFqze2RK0UVARyAqsJR6UC+I4GgaG/10h4oOJXr6DKrGqyVYcIZUrfSorr93qfBe7gGoocFG6TSW15LY6p2r801LCdBWu/USMBnun67t1L60DzTUkopIwSyicOOBhPmeIAlIOiM
    FORGEJO_RUNNER_TOKEN: AgAQeLvgeFV7WeLQRtFDejZ2PAomEOJWlTMzbLcrBwmehyJtu9dpa5fdo0i4rtVKAZ8LQ0NllMQPVVSzVfFJwp8B+79pG4EUHsX/xDqfF5rryLRiXdzqVj/D+Fyy6TWoDlRO8DQsa2YD053PKXNBoMxv/oRJbaWNJf2MOeU798iMXIUqWBn4Fqw+F5C12J/8hUawrW3pMMUmXILbpLayeqDo3Rfe2gBAG+UZ0ahv5nSXpHBPPIj0Zt5Mvxjya3mf23zHKSznShLdWMe6mDFXZEqlvat+MNDOUf2xPIKHDITTKfEXUiTYrgNRarKBunGukDyjYKr/J2InrvzhpEKa/NBxfKD2gGjzLA+nISmg4/NgOfh6TvNqc+fJo/zPORwRkxVo+VjO3uZkeoNkfBLPa0xT62N6Hx3uUtT/oWPOByxuy5F+RurWpWGuxkYM5tmgMya+RcndoH2mYdCtFbIsRXbybRGXzYYtSbSyaOfvf4Z0bDVzckFPKoscBwQIDj8L3Dfm/eO+BaFgbJMZIZ0ZpUCKRWQxPm0RjtJgteh+4c8tpvqHrrhZou9Q2Z7i+McuTou6OgdUCAJlAGl482JrOy3CSOhHbs0gWPmOYB4s8oZJ4gOqw7kg9fDEHZzoIV/NRrDbw66pWEMydGyU368nVfQH/4PhiQDqRBaZqFyMoQGANQMnT2xE1QRzt4Kx4IstK52FLKd+23y2njSn+gLsvOFkcEz4A8Xgi3KC2a4kvLhOoDXtKlTEcO7a
  template:
    metadata:
      name: forgejo-runner-secret
      namespace: forgejo-runner
    type: Opaque
