---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: rotierender-fisch
spec:
  encryptedData:
    .dockerconfigjson: AgBVNNdazhVUPXxxiu3fLLUP1e/z5NNm5Ig4WZd4dhigw8ynde24/BRU2G5cnMH7ndanzukwXZFuKki2vagt6gBUrgr16UR+p0o1rr4iLMppq8Sr4/EHjLFuEaJKLCKtBsiCq1ItF0scmZRcQm/Q5jByHr0NnlCbArwOPDI0vgvJrXlw6XsNiEA4MYn7jmZ1NrxKEtT+6qZnmsWVKiaDGSjIK8BKKhdntVciTHJesz662pL+8HLz1ymEJwFY+tAg5SqRCCjwHnFxzj8B0GFRkpC/mJGBaPYCLO1yGvdpibNKrcboGh4TeNlggQpm7Zsw/Df/6i2IDbZ1NFjsz+oxA3EsSIAsIjgP0iQzraRaLzoYRNfslHxwjzGubSR1/zN4+Hcv8M4Ikj3iiiV+/f7Tx8jJTCrTIQyuppzvUvl10+3pz1ZxhYaW2s57rIbtLGrEXJPrbQPVt7gV8J2mXZN3lRNW3LWQspJ2qiA0XG7eVtJRNkwK9od2oNVhaNmCvEgwFDwuS7AABs+AyBt95/7B6LZzd7YWCrVZYxvcoVNPoqSxBlUYz+YKYjOPX6LWwypBaIhA8TIUA2VCY9yKssCH0Cl5eKT6ZS1FPqWvhzc6R1kBPLxym83Ex3VNk7yt4mupH52QcB7k5dR81BpvUdIDC5lXOQ8n/jd/Fve1d79LcRlNyd9vja3LLePKCZJrPqPioDxdXkXRQzPVwT5apA4Vya8A5gALUV+N/K+7amkIiT8IX99RIC0BQYHtYyHqdGdZX5uHro/D5jT8XdlRVDNZ7UBb1jQfq3UF5j4RI2P0URMW7BPlRRn/mBGS6fRlzzK1rfXkwC1qwmzyqq9UowASEDSxcVcYTcpNm93X
  template:
    metadata:
      name: registry-secret
      namespace: rotierender-fisch
    type: kubernetes.io/dockerconfigjson
