---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-oauth-authentik
  namespace: git
spec:
  encryptedData:
    key: AgCUUC5GZw2Az/RS4qbTW9uTInMei8u+0w6109HGbji+TtVJkADxHmBBjtil0adnW/ZrVs+Cep96i6LeM+70LVn7zCgd65C+C/leVEBDNGNyY5D6IrDO5nD2JEnA4w2dGTx4LJvonz2HfjaKQdSkM52OpV5jeClYzmhbGOpDExIE4Q9mRpER6MM0kLEFEPoIrx3Z907yaHGbSyVrXp0IXDCu+7TGOsktUyclwT8s9xfgQSdgOkQ+3/APJLd8K13IqF7YDrck/kpmk7RqjqFO0BOagpJaE4c5GjzEZjaYoFWwuJT2R/PJ1/wxmsA1UNYE0Q4N7nrMRlkAk/gMopXgY89NeVeVLl9RJ8ckGzrV885+V5Q+FaXAigX9lh04PNunR08RmZTW4aKXqX8nttqpugDJB4KYNW+WySk6PBs8rOVMKyvbmyH1vLD1Zwcm7VXdsR4a9WTIzobMvvhOvzjJn28rbxzngoBKOAflquiI0LUiOnCPVS9MlaA6TW9k6DyvYQSLonb2uNFkK2VPTwP8LCVqjnahoWWiGjZ70n/cRstKzQltxjZM4XDMvc2/RmtzTo34N0Akb2NgDDK4WVfTB9cQ//ixofQZ9sMU7Ur5JgUXS2V0moNRPZBGA3mZBvgcBZ4PjEa+3yHB5yKolo7ZTIpiujnJwkxefZdGRJfBkU3Vl0EoxDpf3Fl6FArLstx9pGFQXVZYvoHLkBMFKAQMnv6rs9JWQLAw2nDsz/TP4MY0B5mTa1cV0f5J
    secret: AgA+bXLUn9HahN7Z61ttHtwHJXFaxG7z1rZR0WR5We60vUijtVUWmdTB1vJUfMy/WuCyrgaD2/tp4p2hEl5VwKEdkTPsiizM83buWGx1MNzQLWDE1hB3CxTf3qBgbKh8/jMVNHG9hGlpFaWkMhPibrJfep8UgSPANen7xhqKYLXoppbG5fy+pllDNiIaw/7Oj7soZJwmOXycqSrUzmaI/a64O1VNIZA4+lDY8VS20MZpVpViCGsjy657l46DvtdCxAvC/9f9pTb7PMOO+7DZ24KWoamnnD7fBVYqeKTtT6xy9hV/cA/K7mBwzoe6Br5up3er9GZKWWgSXITMKDwauQA8ji825SVOlvLt8l5n6ztFBCfynZQMSVWC04OuQkRHTyZzUQ9lbp9ksQb7Tg1Ca4xI8co6J8rOWck1c65/l6F36w6OSVQuuRcOt7xvDPB5GN8sk0QpoC5ArAG+bVnrpaJt648Q6peaKhitDkIXhUPGIfhxAtEXHUyMCYKMbolxO7nra9ECZqo8pQWnlQaEHIwqritAoB+Hy9SPhNj4EFT73K82HUfdPOnNZzEmRLAW/rHDJ5ddAMgA+JrsEgRx1KDPdiDBetmBCxTWIM7z2+oghKu6vtnhARfS5ZkYt/MRrlbDo0RPrpELtZkEqNfIZjG5xHdvQMRgdctKX7uKpqlU7GhBQsXgY4dIj3WMjiOPqyz2XKIVZgnRAWzGKXsyYwO3F3xyKOPLwDDk4U1ZeLAOJdxRcixtHAk1J5P1YPlXa2NDFCH3eCVxGBz3eMQAWfpTFK1tb28FUhpz+FgtNdR9VpDltQfFgzmhDhmHaaO3SSkDFZAoBdLI9Ntprc5XVdeCRD3Qn2i6wYPk0FC0p8S+Yg==
  template:
    metadata:
      name: forgejo-oauth-authentik
      namespace: git
    type: Opaque
