---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: homepage
spec:
  encryptedData:
    .dockerconfigjson: AgB58BhCUdGj12d/CFWob2TEN7nR7/hZb28Xa+igZz3Lp44hyG6gwYvmCzYSrB6HQkbZJR+7Vni2zudNJF/nbi+h9OIB2VGaoRAtA32EfLAqurVU8dm2CDSjmU/fw3k0Ok6pKlevTfBoWLWWOjUzCuclTL7fQRTVNr9QOEqwyktubv8y0gKkr4PbP2RkB5MnXKG2boxgx/NL0GmDxv2P4gcAdV9mO9/QvDQ+aenc3bKdFD8Ab4976floKnmK4yF1QRPPoRTrQ91pqJplHkjmYaRsfkXRu9MggzYIPqYPLFVIDoMxydDMOUp7wUwVzBT2erxwnH7lzgCR4EpvjTSuWc5crwkpENmO9zQQiac1Y3yD7T3K40X1Q/pFOsaiGIZ4Idg2CP9rab6UVMErmgUp6Sk05xtfQCSbl9oeF0tAGkGbMP8ezYvlCyznnPbREgs9q6utwyEdvBxmDVNHtym+9QADw+Ggzh6bzWtoB9YDa9WeLU8M15m3ZX7HMtD8Xj7g65XuDthW3vVL9vxcgakGILmyitFm+9++XY7tK+hHL5HR84i/36EGmBRraAtImcbjTvL3hdVrxUq5/M7dn25MZ5sO06u8yBEHOM2+Ifl5fgfRtZJab+YAY4h1/Y3fPWXa5pfFPFwWxXlQmPxojIcwAxqWOTT4TcSeCP5+ED+9HroGi7sMYAPHQAxB9vvpFCDchdCKdOCVpNEXIJ39Mh/JqFx/KUaPMrq63FXM2v4I4eOVPqWwz51DxYgbVu64ucHlgEpZeiYhZa0/u72x6YkkkUCZQkm+1vStQmRdI/aiKvAYtIKxIz28joiRLrE4/BkGSlSBclGMIOE/hOObtzWGX3VuKMknoqTXaymV
  template:
    metadata:
      name: registry-secret
      namespace: homepage
    type: kubernetes.io/dockerconfigjson
