apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  targetNamespace: ingress
  createNamespace: true
  version: 4.14.1
  valuesContent: |-
    controller:
      config:
          strict-validate-path-type: false
          force-ssl-redirect: true
      extraArgs:
          default-ssl-certificate: ingress/becutewith-me
      service:
        externalTrafficPolicy: Local
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - IPv4
          - IPv6