---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ionos-secret
  namespace: cert-manager
spec:
  encryptedData:
    IONOS_PUBLIC_PREFIX: AgBXALdxZq8ewFyQV4VVSxvWwZbgTFi9EIxZ6OEks2vo8bCbqDGA1lMr/X7/GxzCDYMa2elpnBtM6z/gJN41eSgaOhN6TrnhFQHiwQ81UxO/y+ibeOFCMc+jLDhE8C+/nHezyUyZCsEtk1/AXP2/q8BmvBWD3P49FAmuUoEnu3zVU8qUJg0YTH0XIRYk5qV7SzYNdC/D+ioLnBkH9ti3hoGTMBNwKp/6Di0XrJJ0EURNqeNxyPFFBKGuioeOxZq5sTU/vXJyn5yIMGB0paL48Xq5gt+2mMd03an7NpTmuKuyv8CrtzegOpuZ7vUuSrabbPfZfNN3c06fW6d4d1SfVVY9NR3ISiVUdi37txiRj1itzMMjX4UXUcqU4V+c+Hm8Af9k0HjCGpfD3B/pBNqNk4zlkvnbX+3Zxt4ZFwumruJV9/tAsbnK4LGj/hhRldAXNmTdRUvPHiygKP191JmSUVYTFnIav+zn+0z5yXE7IYG7ItbpLMyVL2n8MmF9BBpisTRnaQjtBvw1VSzmEwibnEksuJM4CIkJCwg+TwWyMDvUBpT2anHddB6oayLwX+mufAqFfhYbKF3Ryw3y2dKj03ZWRiCZ4bw5o9v3+TMtXANukLk8Y3FSPa5fZN/HbRanj6Whs/ZBidICIsoQUfdiYQPc4nA61f9Ap5l7mtPcehfSmQkm12TM6kQggKvAXY2hWb0rw8NlAHoVoJif76PByqZsDI60aVawRMEDguqxNrvZIw==
    IONOS_SECRET: AgABgWw1odvKNc9LAPHC0mRici7m5LFUL8YUGMVzTedNPdMhgoFFrRVoBnEmZgXCx+RoSj8B67jIkT3HU77rMlpaUiSXmjnXC8HRdEDsEYQ6jOnVnNLH9iCUAXLFyNbm1eiV6/PbS+yA2yg2DHvDFN+JEq/mokLPhAx4eJ0mWtWL9KzcVGrHF26hU/TpD/6IFtNaf20SSFyGyqkWjHbdfgZsZ30y9LA8ba1ti7+mRBgHI/Qi0qve8Dy1OTYHzEdqOTukqGTjZRDX6CF/FXdFhNZpyG1Wv3uZuAy/1zlXJ6TCcoI64RvSxas7bw2bHy5mUtl0vyxTnff396v88EoUCwbRu3bWnMUFl0GEgBbNbum/lnTijeqoRDTPhAXuWzIovNPKXNL7zTUv7XK9h6KM5LJfkm5Wwq+AomYxV9qi38+XtVt8ILxHI6AsbC2erjjBpwm5FEbZup3S+Q/gzQX2/4G/3BGUMZ99BTJvpsCH828rGkoW3Ir4lqugxwkYBb0gEEmoULteUxEDMTgfMy50nFcJtrDW2ItSoCeuR+in25UbJc7DK685WVVY+LOrEp2bBUjVBzY1PCdgZE7ivxR8o6SvGRhrPtdh4TVAI82dQaQez+V87rqW1BMwF30S78Fvp1VNnpDXgI0OdPga12utV3qRTqLo5GwlvRgUYD+m+4vn0oVUeQmR+PK7WhgWPp2XJXCAJe5ToEbDfpXg9hK7A90HMjdVEO0VJ4rhtwHXlMdlu8ylxH8qHqs4f9jkXVYGgooS1DJ+kSt8zpLThbs2UKGUsaCdkCzF5ZUxFLpz6WvOan7VwNudYg==
  template:
    metadata:
      name: ionos-secret
      namespace: cert-manager
    type: Opaque
