apiVersion: v1
kind: ConfigMap
metadata:
  name: foodtracker-config
  namespace: foodtracker
data:
  DATABASE_PATH: /data/foodtracker.db
  ORIGIN: https://foodtracker.becutewith.me
  BETTER_AUTH_URL: https://foodtracker.becutewith.me
  OIDC_DISCOVERY_URL: https://auth.becutewith.me/application/o/food-tracking-app/.well-known/openid-configuration
  OIDC_CLIENT_ID: MZkC82EGQDnpLpd5PdBYFaPvAchegZfgdkggXwrj
